In [2]:
import xarray as xr
import numpy as np
import geopandas as gpd
import rasterio
import rioxarray as rio
from rasterstats import zonal_stats
import pandas as pd
from mpl_toolkits.basemap import Basemap
import matplotlib.pyplot as plt
from shapely.geometry import mapping
import regionmask
from netCDF4 import Dataset
import cartopy.crs as ccrs
from scipy import interpolate

C:\Users\User\anaconda3\lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,


In [3]:
# The following command is for data with single varialbe
ds = xr.open_dataset("C:\proj sif\TROPOSIF_L2B_2020-01-01.nc", group= 'PRODUCT')
ds

<xarray.Dataset>
Dimensions:        (time: 1, n_elem: 3092691)
Coordinates:
  * time           (time) datetime64[ns] 2020-01-01
Dimensions without coordinates: n_elem
Data variables:
    delta_time     (n_elem) datetime64[ns] ...
    SIF_743        (n_elem) float32 ...
    SIF_Corr_743   (n_elem) float32 ...
    SIF_ERROR_743  (n_elem) float32 ...
    SIF_735        (n_elem) float32 ...
    SIF_Corr_735   (n_elem) float32 ...
    SIF_ERROR_735  (n_elem) float32 ...
    latitude       (n_elem) float32 ...
    longitude      (n_elem) float32 ...

In [4]:
SIF_743 = ds['SIF_743'].values
SIF_743

array([0.7626782 , 0.31396365, 0.17063966, ..., 0.09132421, 0.30846646,
       1.0057812 ], dtype=float32)

In [18]:
import numpy as np

n_elem = 3092691

# Find the closest factor of n_elem
factors = np.array([i for i in range(1, int(np.sqrt(n_elem)) + 1) if n_elem % i == 0])
n_lat = factors[np.argmin(np.abs(factors - int(np.sqrt(n_elem))))]
n_lon = int(n_elem / n_lat)

# Create a one-dimensional numpy array
data_1d = np.arange(n_elem)

# Reshape the one-dimensional array into a two-dimensional array
data_2d = np.reshape(data_1d, (n_lat, n_lon))


In [20]:
data_1d

array([      0,       1,       2, ..., 3092688, 3092689, 3092690])

In [19]:
data_2d

array([[      0,       1,       2, ...,    8660,    8661,    8662],
       [   8663,    8664,    8665, ...,   17323,   17324,   17325],
       [  17326,   17327,   17328, ...,   25986,   25987,   25988],
       ...,
       [3066702, 3066703, 3066704, ..., 3075362, 3075363, 3075364],
       [3075365, 3075366, 3075367, ..., 3084025, 3084026, 3084027],
       [3084028, 3084029, 3084030, ..., 3092688, 3092689, 3092690]])